# Generated by Django 3.1 on 2025-09-29 03:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewrating',
            unique_together={('user', 'product')},
        ),
    ]
